name: edukit-bot-kyrofa
version: '1.0'
summary: ROS system for teleoperating edukit bot
description: |
  A ROS system for teleoperating the EduKit #3, the robotics kit. This
  accompanies the "Your First Robot" series written by Kyle Fazzari:

      https://kyrofa.com/posts/your-first-robot-a-beginner-s-guide-to-ros-and-ubuntu-core-1-5

  Note that the `joystick` interface is needed for access to the gamepad, and
  the `physical-memory-control` interface is needed for access to GPIO. Both
  of these interfaces must be connected before this snap will function:

      $ sudo snap connect edukit-bot-kyrofa:joystick
      $ sudo snap connect edukit-bot-kyrofa:physical-memory-control

grade: stable
confinement: strict

# Workaround for LP: #1677002.
build-packages: [lsb-release]

parts:
  workspace:
    plugin: catkin
    rosdistro: kinetic
    source: .
    catkin-packages: [edukit_bot]
    # Required to build RPi.GPIO
    build-packages: [python-dev, python-setuptools]

apps:
  launch:
    command: roslaunch edukit_bot edukit_bot.launch
    daemon: simple
    plugs:
      # Basic networking
      - network
      - network-bind

      # Needed for access to gamepad
      - joystick

      # Needed for GPIO memory-mapping
      - physical-memory-control
